services:
  app:
    depends_on:
      - db
    build:
      context: .
    container_name: api-double-track
    networks:
      - mynet
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@dtrack_db:5432/dbtrack?sslmode=disable
      PORT: 8080
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres
    container_name: dtrack_db
    hostname: dtrack_db
    networks:
      - mynet
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbtrack

volumes:
  pgdata:

networks:
  mynet:
    driver: bridge
